name: hybrid-nginx-custom-workflow

on:
  push:
    branches:
      # - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: owlenjoyer/nginx-custom

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest
